from figure_scraper.website import Website

from figure_scraper.alter import Alter
from figure_scraper.amakuni import Amakuni
from figure_scraper.amiami import AmiAmi
from figure_scraper.animaru import Animaru
from figure_scraper.animate import Animate
from figure_scraper.aniplexplus import AniplexPlus
from figure_scraper.bellhouse import BellHouse
from figure_scraper.cospa import Cospa
from figure_scraper.curtain_damashii import CurtainDamashii
from figure_scraper.fnex import Fnex
from figure_scraper.gamers import Gamers
from figure_scraper.goodsmile import Goodsmile
from figure_scraper.graffart import GraffArt
from figure_scraper.granup import Granup
from figure_scraper.hobbysearch import HobbySearch
from figure_scraper.hobbystock import HobbyStock
from figure_scraper.kotobukiya import Kotobukiya
from figure_scraper.medicos import Medicos
from figure_scraper.msfactory import MSFactory
from figure_scraper.neowing import Neowing
from figure_scraper.penguinparade import PenguinParade
from figure_scraper.union_creative import UnionCreative
from figure_scraper.wave import WaveCorporation
