from figure_scraper.website import Website

from figure_scraper.alter import Alter
from figure_scraper.amakuni import Amakuni
from figure_scraper.amiami import AmiAmi
from figure_scraper.amnibus import Amnibus
from figure_scraper.animaru import Animaru
from figure_scraper.animate import Animate
from figure_scraper.aniplexplus import AniplexPlus
from figure_scraper.bellhouse import BellHouse
from figure_scraper.charasupply import CharaSupply
from figure_scraper.cocollabo import Cocollabo
from figure_scraper.cospa import Cospa
from figure_scraper.crux import Crux
from figure_scraper.curtain_damashii import CurtainDamashii
from figure_scraper.dashstore import Dashstore
from figure_scraper.dezaegg import Dezaegg
from figure_scraper.dmmscratch import DmmScratch
from figure_scraper.eeostore import EeoStore
from figure_scraper.ensky import Ensky
from figure_scraper.fnex import Fnex
from figure_scraper.gamers import Gamers
from figure_scraper.goodsmile import Goodsmile
from figure_scraper.graffart import GraffArt
from figure_scraper.granup import Granup
from figure_scraper.hobbysearch import HobbySearch
from figure_scraper.hobbystock import HobbyStock
from figure_scraper.kotobukiya import Kotobukiya
from figure_scraper.kujibikido import Kujibikido
from figure_scraper.medicos import Medicos
from figure_scraper.msfactory import MSFactory
from figure_scraper.neowing import Neowing
from figure_scraper.penguinparade import PenguinParade
from figure_scraper.quesq import Quesq
from figure_scraper.stellanotes import StellaNotes
from figure_scraper.tapioca import Tapioca
from figure_scraper.union_creative import UnionCreative
from figure_scraper.wave import WaveCorporation
from figure_scraper.yyworld import YYWorld
