# Base folder to hold all folders representing different website
FOLDER_BASE = 'download'

FOLDER_ALTER = FOLDER_BASE + '/alter'
FOLDER_AMAKUNI = FOLDER_BASE + '/amakuni'
FOLDER_AMIAMI = FOLDER_BASE + '/amiami'
FOLDER_ANIMARU = FOLDER_BASE + '/animaru'
FOLDER_ANIMATE = FOLDER_BASE + '/animate'
FOLDER_ANIPLEXPLUS = FOLDER_BASE + '/aniplexplus'

FOLDER_BELLHOUSE = FOLDER_BASE + '/bellhouse'
SUBFOLDER_BELLHOUSE_IMAGES = '/images'
SUBFOLDER_BELLHOUSE_NEWS = '/news'

FOLDER_COSPA = FOLDER_BASE + '/cospa'

FOLDER_CURTAIN_DAMASHII = FOLDER_BASE + '/curtain-damashii'
SUBFOLDER_CURTAIN_DAMASHII_IMAGES = '/images'
SUBFOLDER_CURTAIN_DAMASHII_TAG = '/tag'
SUBFOLDER_CURTAIN_DAMASHII_EVENT = '/event'

FOLDER_FNEX = FOLDER_BASE + '/fnex'
FOLDER_GAMERS = FOLDER_BASE + '/gamers'
FOLDER_GOODSMILE = FOLDER_BASE + '/goodsmile'
FOLDER_HOBBYSEARCH = FOLDER_BASE + '/hobbysearch'
FOLDER_HOBBYSTOCK = FOLDER_BASE + '/hobbystock'
FOLDER_KOTOBUKIYA = FOLDER_BASE + '/kotobukiya'
FOLDER_MEDICOS = FOLDER_BASE + '/medicos'
FOLDER_NEOWING = FOLDER_BASE + '/neowing'
FOLDER_PENGUINPARADE = FOLDER_BASE + '/penguinparade'
FOLDER_UNION_CREATIVE = FOLDER_BASE + '/union-creative'

FOLDER_WAVE = FOLDER_BASE + '/wave'
SUBFOLDER_WAVE_IMAGES = '/images'
SUBFOLDER_WAVE_GUESS = '/guess'

DOWNLOAD_LOG_FILE = 'download_log.tsv'

WEBSITE_TITLE_BASE = 'Website'

WEBSITE_TITLE_ALTER = 'Alter'
WEBSITE_TITLE_AMAKUNI = 'Amakuni'
WEBSITE_TITLE_AMIAMI = 'AmiAmi'
WEBSITE_TITLE_ANIMARU = 'Animaru'
WEBSITE_TITLE_ANIMATE = 'Animate'
WEBSITE_TITLE_ANIPLEXPLUS = 'Aniplex+'
WEBSITE_TITLE_BELLHOUSE = 'Bell House'
WEBSITE_TITLE_COSPA = 'Cospa'
WEBSITE_TITLE_CURTAIN_DAMASHII = 'Curtain Damashii'
WEBSITE_TITLE_FNEX = 'F:Nex'
WEBSITE_TITLE_GAMERS = 'Gamers'
WEBSITE_TITLE_GOODSMILE = 'Goodsmile Company'
WEBSITE_TITLE_HOBBYSEARCH = 'Hobby Search'
WEBSITE_TITLE_HOBBYSTOCK = 'Hobby Stock'
WEBSITE_TITLE_KOTOBUKIYA = 'Kotobukiya'
WEBSITE_TITLE_MEDICOS = 'Medicos Entertainment'
WEBSITE_TITLE_NEOWING = 'Neowing (CDJapan)'
WEBSITE_TITLE_PENGUINPARADE = 'Penguin Parade'
WEBSITE_TITLE_UNION_CREATIVE = 'Union Creative'
WEBSITE_TITLE_WAVE = 'Wave Corporation'

SUBFOLDER_COSPA_SCAN = FOLDER_COSPA
FILE_COSPA_SCAN_OUTPUT = SUBFOLDER_COSPA_SCAN + '/scan.txt'

MAX_PROCESSES = 30
